# Research Paper Search and Summarization

In [125]:
!pip install datasets

## 1. Data Loading and Preprocessing


In [126]:
from datasets import load_dataset

In [127]:
dataset=load_dataset("CShorten/ML-ArXiv-Papers",split='train')



In [128]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})


In [129]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rat

In [130]:
import pandas as pd

In [131]:
df=pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [132]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [133]:
df=df[['title','abstract']]

In [134]:
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
117587,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [135]:
# Reduce the no of rows
df=df.head(15000)
df

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th..."
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...


In [136]:
df.isnull().sum()

,0
title,0
abstract,0


In [137]:
df["paper_text"]=df["title"]+" "+df["abstract"]
df

/tmp/ipykernel_8364/3936252372.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["title"]+" "+df["abstract"]


,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...


In [138]:
# converting into dataframe
df[["paper_text"]].head()

,paper_text
0,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [139]:
type(df[["paper_text"]].head())

pandas.core.frame.DataFrame

In [140]:
print(df["paper_text"].iloc[0])

Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regress

In [141]:
from sentence_transformers import SentenceTransformer

## 2. Generating Sentence Embeddings


In [142]:
# 1. Load a pretrained Sentence Transformer model

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

In [143]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>


In [144]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparam

In [145]:
# Removed \n(new line) so that model does not become confuse with \n
df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)
df

/tmp/ipykernel_8364/1813364570.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.replace("\n"," ",regex=False)


,title,abstract,paper_text
0,Learning from compressed observations,The problem of statistical learning is to co...,Learning from compressed observations The pr...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun...",Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...,Parametric Learning and Monte Carlo Optimizati...
...,...,...,...
14995,Estimation of a Low-rank Topic-Based Model for...,We consider the problem of estimating the la...,Estimation of a Low-rank Topic-Based Model for...
14996,A Comparison of Audio Signal Preprocessing Met...,"In this paper, we empirically investigate th...",A Comparison of Audio Signal Preprocessing Met...
14997,Implicit Regularization in Deep Learning,In an attempt to better understand generaliz...,Implicit Regularization in Deep Learning In ...
14998,A Quasi-isometric Embedding Algorithm,The Whitney embedding theorem gives an upper...,A Quasi-isometric Embedding Algorithm The Wh...


In [146]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regres

In [147]:
# Removed white spaces in front and last
df["paper_text"]=df["paper_text"].str.strip()

/tmp/ipykernel_8364/1640325731.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["paper_text"]=df["paper_text"].str.strip()


In [148]:
df["paper_text"].iloc[0]

'Learning from compressed observations   The problem of statistical learning is to construct a predictor of a random variable $Y$ as a function of a related random variable $X$ on the basis of an i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable predictors are drawn from some specified class, and the goal is to approach asymptotically the performance (expected loss) of the best predictor in the class. We consider the setting in which one has perfect observation of the $X$-part of the sample, while the $Y$-part has to be communicated at some finite bit rate. The encoding of the $Y$-values is allowed to depend on the $X$-values. Under suitable regularity conditions on the admissible predictors, the underlying family of probability distributions and the loss function, we give an information-theoretic characterization of achievable predictor performance in terms of conditional distortion-rate functions. The ideas are illustrated on the example of nonparametric regres

In [149]:
# 2. Calculate embeddings by calling model.encode()
embeddings = model.encode(sample_text)
print(embeddings.shape)
print(type(embeddings))

(384,)
<class 'numpy.ndarray'>


In [150]:
embeddings

array([-1.31564081e-01, -6.78268261e-03, -3.67608899e-03,  3.26516181e-02,
        1.12196378e-01,  1.22726625e-02,  9.81672332e-02, -9.00522768e-02,
        4.23116535e-02, -1.97735038e-02, -3.30841728e-02,  7.45293945e-02,
        1.06320381e-01, -2.06043050e-02, -2.05210242e-02,  1.69492350e-03,
        7.08194748e-02,  5.85444868e-02, -1.12319104e-01,  2.08246931e-02,
        5.69254532e-02,  2.01578029e-02,  2.58310027e-02,  3.21702920e-02,
        1.05137683e-01, -9.67675969e-02,  2.70080213e-02, -2.34509017e-02,
       -4.54967879e-02, -1.01369787e-02, -1.79485511e-02, -4.81442735e-02,
        1.07765254e-02, -3.75906937e-02,  1.94347762e-02,  3.71518992e-02,
        2.96784285e-02,  4.33094352e-02,  4.37320806e-02,  3.70486639e-02,
       -1.82593311e-03,  4.55186190e-03, -7.99066573e-03,  3.03737260e-02,
       -1.43779982e-02,  3.79514992e-02,  5.95916100e-02, -2.58336067e-02,
       -6.52156994e-02,  5.90026602e-02, -2.10713837e-02,  7.35942796e-02,
       -5.72010837e-02,  

In [151]:
embeddings[:16]

array([-0.13156408, -0.00678268, -0.00367609,  0.03265162,  0.11219638,
        0.01227266,  0.09816723, -0.09005228,  0.04231165, -0.0197735 ,
       -0.03308417,  0.07452939,  0.10632038, -0.0206043 , -0.02052102,
        0.00169492], dtype=float32)

In [152]:
# top 5 lekar usko list meh convert kar diya
sample_embedding=model.encode(df["paper_text"].head(5).to_list())
sample_embedding

array([[-0.13156408, -0.00678267, -0.00367612, ...,  0.09561247,
        -0.04423936,  0.00522619],
       [-0.03589674, -0.06343269, -0.00394962, ...,  0.07206136,
        -0.13262011, -0.00412081],
       [-0.08129282,  0.02410301, -0.0886826 , ..., -0.04524422,
        -0.04765854, -0.01549939],
       [-0.10218995, -0.06282566,  0.03273677, ..., -0.03118814,
         0.03174182,  0.03621244],
       [-0.08391044,  0.01838461, -0.01556659, ..., -0.01188401,
        -0.10644458,  0.00790993]], dtype=float32)

In [153]:
print(sample_embedding.shape)

(5, 384)


## 3. Cosine Similarity
This subsection demonstrates how cosine similarity can be used to measure the similarity between two embeddings. A higher cosine similarity score indicates greater semantic resemblance.

## Insights
5 --> because we took head(5)



In [154]:
from sklearn.metrics.pairwise import cosine_similarity

In [155]:
# Cosine similarity expects 2D
# Here reshape(1,-1) --> take 1 row and adjust the columns to the remaining ones
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[0].reshape(1,-1))
similarity


array([[1.]], dtype=float32)

In [156]:
similarity=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[1].reshape(1,-1))
similarity


array([[0.36625272]], dtype=float32)

In [157]:
# Calculating similarity for first 5
for i in range(1,5):
  sim=cosine_similarity(sample_embedding[0].reshape(1,-1),sample_embedding[i].reshape(1,-1))
  print(sim)

[[0.36625272]]
[[0.3352284]]
[[0.15505117]]
[[0.37421536]]


## Insights
4th wala paper is most similar to the 1st paper

## Generate full embedding for 15000

## 4. FAISS Indexing for Efficient Search
This section uses the FAISS (Facebook AI Similarity Search) library to create an efficient index for the entire dataset's embeddings. This allows for fast similarity searches, which is crucial for large datasets. The embeddings and the FAISS index are saved to disk for persistence, avoiding regeneration on subsequent runs.

In [158]:
# batch_size is used so that we don't do embedding all at once nd break them into batches and then do the embedding
# This method is used so that all RAM does not eats up
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings")
    embeddings = np.load("paper_embeddings.npy")
else:
    print("Generating embeddings")
    embeddings = model.encode(
        df["paper_text"].tolist(),
        batch_size=32,
        show_progress_bar=True
    )
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

Loading saved embeddings


In [159]:
if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index")
    index = faiss.read_index("paper_faiss.index")
else:
    print("Creating new FAISS index")
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(embeddings)
    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

Loading existing FAISS index


FAISS --> It creates a special search structure

Cosine Similarity --> dot product hota hai

FAISS --> Inner product hota hai

L2 Normalization

In [160]:
!pip install faiss-cpu

In [161]:
import faiss

In [162]:
# Normalise embedding
# faiss.normalize_L2(embedding)

In [163]:
# Create index
# Here IP means Inner Product it means it creates inner product for all embeddings
# index=faiss.IndexFlatIP(384)
# index

In [164]:
# Add the L2 normalized embeddings to the FAISS index.
# This prepares the index for efficient similarity searches.
# index.add(embedding)

In [165]:
# print(index.ntotal)

In [166]:
# Create embedding for a query
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
print(query_embedding.shape)

(1, 384)


In [167]:
# Normalize the query_embedding
faiss.normalize_L2(query_embedding)

In [168]:
# To search how closely our query matches with the stored vectors of the research papers
D,I=index.search(query_embedding,5)
print(D) # Similarity Score --> tells us the similarity score between our query nd the reseach papers stored in the FAISS
print(I) # Indices --> It tells konse paper no seh it is similar

[[0.6807246  0.67092216 0.6521999  0.62811756 0.6131154 ]]
[[10466 13730 11873 12691 11282]]


Here, we display the top matching research papers found by the FAISS index based on the query. We show the similarity score, title, and the beginning of the abstract for each paper.

In [169]:
print(df.iloc[10466 ]["title"])

A Perspective on Deep Imaging


In [170]:
print(df.iloc[10466 ]["abstract"])

  The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.



In [171]:
print(df.iloc[11873]["title"])

Classification of MRI data using Deep Learning and Gaussian
  Process-based Model Selection


In [179]:
def search_paper(query, k=5):
    query_embedding = model.encode([query])
    faiss.normalize_L2(query_embedding)

    D, I = index.search(query_embedding, k)

    for score, idx in zip(D[0], I[0]):
        print("Similarity Score:", score)
        print("Title:", df.iloc[idx]["title"])
        print("Abstract:", df.iloc[idx]["abstract"][:500])
        print()

In [181]:
search_paper("deep learning for medical image analysis")

Similarity Score: 0.6807246
Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance

Similarity Score: 0.67092216
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of
expertise to ensure proper convergence. A promising alternative is to fine-tune
a CNN that has been pre-trained using, for insta

In [173]:
!pip install transformers==4.46.3

## 5. Abstract Summarization with Hugging Face Transformers
This section integrates a pre-trained summarization model from the Hugging Face Transformers library to generate concise summaries of the retrieved paper abstracts. This enhances the utility of the search by providing quick overviews of relevant papers.

In [175]:
from transformers import pipeline
summarizer=pipeline(
    task="summarization",
    model="facebook/bart-large-cnn",
    device=0
)

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [176]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

This helper function `search_paper` encapsulates the entire search logic: encoding the query, normalizing it, performing the FAISS search, and then printing the detailed results including similarity scores, titles, and truncated abstracts.

In [182]:
summary=summarizer(df.iloc[10466]["abstract"],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]


In [183]:
type(summary)

list

In [185]:
type(summary[0])

dict

In [186]:
type(summary[0]["summary_text"])

str

In [187]:
print(summary[0]["summary_text"])

The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.


In [190]:
for score, idx in zip(D[0], I[0]):
    print("Similarity Score:", score)
    print("Title:", df.iloc[idx]["title"])
    print("Abstract:", df.iloc[idx]["abstract"][:500])

    summary=summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40)
    print(summary)
    print(summary[0]["summary_text"])
    print()

Similarity Score: 0.6807246
Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance


You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


[{'summary_text': 'The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.'}]
The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might lead to intelligent utilization of domain knowledge from big data, innovativeapproaches for image reconstruction, and superior performance in clinical applications.

Similarity Score: 0.67092216
Title: Convolutional Neural Networks for Medical Image Analysis: Full Training
  or Fine Tuning?
Abstract:   Training a deep convolutional neural network (CNN) from scratch is difficult
because it requires a large amount of labeled training data and a great deal of


This final loop combines the FAISS search results with the summarization pipeline. For each top matching paper, it not only displays the similarity score, title, and abstract but also generates and prints a concise summary of the abstract using the `summarizer`.